# Generated by Django 4.0.6 on 2022-07-22 13:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('check', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solver',
            old_name='problem_num',
            new_name='prob_num',
        ),
        migrations.AlterUniqueTogether(
            name='solver',
            unique_together={('user', 'prob_num')},
        ),
    ]
