# Generated by Django 3.0.8 on 2020-07-19 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('check', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waffle',
            name='prob1_ans',
        ),
        migrations.RemoveField(
            model_name='waffle',
            name='prob1_input',
        ),
        migrations.RemoveField(
            model_name='waffle',
            name='prob2_ans',
        ),
        migrations.RemoveField(
            model_name='waffle',
            name='prob2_input',
        ),
        migrations.CreateModel(
            name='Solver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_num', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_num', models.IntegerField()),
                ('question', models.TextField(null=True)),
                ('answer', models.TextField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
