# Generated by Django 3.0.8 on 2020-07-19 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0002_auto_20200719_1639'),
    ]

    operations = [
        migrations.RenameField(
            model_name='waffle',
            old_name='grade',
            new_name='year',
        ),
    ]
