# Generated by Django 3.0.11 on 2020-12-27 13:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0003_auto_20200719_1835'),
    ]

    operations = [
        migrations.RenameField(
            model_name='waffle',
            old_name='year',
            new_name='grade',
        ),
        migrations.AddField(
            model_name='waffle',
            name='last_visit',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 27, 13, 23, 11, 973615)),
        ),
    ]
