# Generated by Django 4.0.6 on 2022-07-21 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='credential',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='major',
            field=models.CharField(choices=[('컴퓨터공학부', '컴퓨터공학부'), ('건설환경공학부', '건설환경공학부')], max_length=30, null=True),
        ),
    ]
