server {
        # listen 80 default_server;
        # listen [::]:80 default_server;

        # SSL configuration
        #
        listen 443 ssl default_server;
        listen [::]:443 ssl default_server;
        ssl on;
        ssl_certificate /etc/letsencrypt/live/waffle-recruit.shop/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/waffle-recruit.shop/privkey.pem;
        root /var/www/html;

        # Add index.php to the list if you are using PHP
        index index.html index.htm index.nginx-debian.html;

        server_name waffle-recruit.shop;

        location / {
                 #First attempt to serve request as file, then
                 #as directory, then fall back to displaying a 404.
                try_files $uri $uri/ /index.html;
        }
        location /check {
                proxy_pass http://localhost:8000/check;
        }
}
server {
    listen           80;
    listen           [::]:80;
    server_name      waffle-recruit.shop;
    return           301 https://www.waffle-recruit.shop$request_uri;
}